name: deploy cloudflare pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"

      - name: clone spa repository
        run: git clone https://github.com/calloc134/reserv-frontend-lab
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./reserv-frontend-lab
      - name: Build
        run: VITE_APP_PATH='/reservations/' pnpm run build
        working-directory: ./reserv-frontend-lab

      - name: create output directory
        run: mkdir -p ./public/reservations
      - name: copy spa build files
        run: cp -r ./reserv-frontend-lab/dist/* ./public/reservations/
      - name: copy html files
        run: |
          cp ./*.html ./public
          cp -r ./css ./public/css

      - name: add redirect rule on reservations dir
        run: echo '/reservations/* /reservations/index.html 200' > ./public/_redirects

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: html-final
          directory: ./public
          githubToken: ${{ secrets.GITHUB_TOKEN }}
